base_url = "https://fribyte.no"

title = "friByte"
description = "friByte er en studentorganisasjon med mål om å drive IT-drift for andre studentorganisasjoner i Bergen. Vi tilbyr rimelige web- og IT-tjenester tilpasset studentorganisasjoner."

default_language = "no"

compile_sass = true
build_search_index = false

generate_feed = true
feed_filename = "rss.xml"

minify_html = true

taxonomies = [
  { name = "categories", feed = false }
]

[markdown]
highlight_code = true

external_links_target_blank = true

[languages.en]
build_search_index = true
description = "friByte is a student organization with the goal of running IT operations for other student organizations in Bergen. We offer affordable web and IT services tailored to student organizations."

[extra]
nav = [
  { name = "Tjenester", path = "@/tjenester.md" },
  { name = "Kontakt", path = "@/kontakt/index.md" },
  { name = "Om oss", path = "@/om.md" },
  { name = "Dokumenter", path = "@/dokumenter/_index.md" }, 
]

footer = [
  { name = "Våre klienter", path = "@/klienter.md" },
  { name = "Bli medlem", path = "@/bli-medlem.md" },
  { name = "Nyheter", path = "@/nyheter/_index.md" },
]

social_media = [
  { name = "Twitter", url = "https://twitter.com/fribyte" }
]

email_general = "post@fribyte.no"
email_join = "bli-medlem@fribyte.no"
email_support = "hjelp@fribyte.no"
